name: Deploy static content to Pages

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the code
        uses: actions/checkout@v3
      - name: Downloading musl-based toolchain
        run: wget https://musl.cc/x86_64-linux-musl-native.tgz
      - name: Extracting musl-based toolchain
        run: tar xzf ./x86_64-linux-musl-native.tgz
      - name: Installing lcov
        run: sudo apt install lcov
      - name: Running the testsuite
        run: make -C tests clean coverage
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './tests/coverage/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

