name: Check that the README is up to date

on:
  pull_request:
  push:

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the code
        uses: actions/checkout@v3
      - run: |
          for function in $(find include/ -type f -exec sed -n 's/^_FORTIFY_FN(\([^)]\+\)).*/\1/p' '{}' ';' | sort | uniq)
          do
          	grep "\`$function\`" README.md || (echo "Please add \`$function\` to the README.md file." && exit 1)
          done

