name: Test suite
on:
  pull_request:
  push:
  schedule:
    - cron: '0 16 * * 5'

jobs:
  gcc:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the code
        uses: actions/checkout@v3
      - name: Downloading musl-based toolchain
        run: wget https://musl.cc/x86_64-linux-musl-native.tgz
      - name: Extracting musl-based toolchain
        run: tar xzf ./x86_64-linux-musl-native.tgz
      - name: Running the testsuite
        run: make -C tests gcc | grep -zqv FAIL

  clang:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [12, 13, 14]
    steps:
      - name: Checking out the code
        uses: actions/checkout@v3
      - name: Setting up clang version
        run: |
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-${{ matrix.version }} 100
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-${{ matrix.version }} 100
      - name: Running the testsuite
        run: make -C tests clang | grep -zqv FAIL
